#include "game.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum
{
  START,
  PLAY,
  WIN,
  LOSE,
} GBAState;

int main(void)
{
  Player character;
  character.health = 3;
  character.row = 10;
  character.col = 10;

  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;

  while (1)
  {
    if (character.health == 0){
      state = LOSE;
    }

    char str1[16]; // this will allocate memory while defination
    sprintf(str1, "You have %d lives", character.health);
    // printf(health);
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();
    switch (state)
    {
    case START:
      if (KEY_DOWN(BUTTON_B, currentButtons) && !KEY_DOWN(BUTTON_B, previousButtons))
      {
        drawCenteredString(HEIGHT / 2, WIDTH / 2, 0, 10, str1, WHITE);
      }
      if (KEY_DOWN(BUTTON_A, currentButtons) && !KEY_DOWN(BUTTON_A, previousButtons))
      {
        fillScreenDMA(BLACK);
        character.health = character.health - 1;
      }

      // state = ?
      break;
    case PLAY:

      // state = ?
      break;
    case WIN:

      // state = ?
      break;
    case LOSE:
    fillScreenDMA(BLACK);
      // drawImageDMA(character.row,character.col, LYN_WIDTH,LYN_HEIGHT,Lyn);
      if (KEY_DOWN(BUTTON_UP, currentButtons) && !KEY_DOWN(BUTTON_UP, previousButtons))
      {
        character.row -=10;
      }
      if (KEY_DOWN(BUTTON_DOWN, currentButtons) && !KEY_DOWN(BUTTON_DOWN, previousButtons))
      {
        character.row +=10;
      }
      if (KEY_DOWN(BUTTON_LEFT, currentButtons) && !KEY_DOWN(BUTTON_LEFT, previousButtons))
      {
        character.col -=10;
      }
      if (KEY_DOWN(BUTTON_RIGHT, currentButtons) && !KEY_DOWN(BUTTON_RIGHT, previousButtons))
      {
        character.col +=10;
      }
      // state = ?
      break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }
  UNUSED(character);

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
