#include "game.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/Title.h"
#include "images/Map.h"
#include "images/Battle-Grass.h"
#include "images/Battle-Castle.h"
#include "images/Rules-Background.h"
#include "images/Character-Select.h"
#include "images/Lose.h"
#include "images/Win.h"
#include "images/Arrow.h"
#include "images/FemaleSprite.h"
#include "images/FemaleSprite2.h"
#include "images/FemaleSprite3.h"
#include "images/MaleSprite1.h"
#include "images/MaleSprite2.h"
#include "images/MaleSprite3.h"
#include "images/Boss1.h"
#include "images/Boss2.h"
#include "images/Boss3.h"
#include "images/Enemy1.h"
#include "images/Enemy2.h"
#include "images/Enemy3.h"
#include "images/Enemy4.h"
#include "images/Enemy5.h"
#include "images/Enemy6.h"
#include "images/FemaleFight.h"
#include "images/MaleFight.h"
#include "images/FemaleCastle.h"
#include "images/MaleCastle.h"
#include "images/General.h"
#include "images/Pirate.h"
#include "images/Sniper.h"
#include "images/FullHearts.h"
#include "images/TwoHearts.h"
#include "images/OneHeart.h"

// Add any additional states you need for your app.
typedef enum
{
  START,
  DRAWRULES,
  RULES,
  DRAWSELECT,
  SELECT,
  DRAWMAP,
  MAP,
  GRASSANIM,
  FIGHT,
  WAIT,
  CASTLEANIM,
  BOSSFIGHT,
  WIN,
  LOSE,
} GBAState;

void changeSprite(Character *a);
void changeSpriteBoss(Boss *a);
void startBattle(Character *a, Character *b, Character *c, Boss *d, GBAState *statePtr);
int checkBounds(int row, int col);

int main(void)
{

  int enemiesLeft = 3;
  Character player;
  Character enemy1;
  char left[20];
  Character enemy2;
  ArrowSelect gender;
  ArrowSelect rps;
  Boss boss;

  gender.row = 126;
  gender.col = 16;

  rps.row = 126;
  rps.col = 16;

  for (int i = 0; i < 1054; i++)
  {
    boss.sprite1[i] = Boss1[i];
    boss.sprite2[i] = Boss2[i];
    boss.sprite3[i] = Boss3[i];
  }

  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;

  while (1)
  {

    currentButtons = BUTTONS; // Load the current state of the buttons

    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    waitForVBlank();
    switch (state)
    {

    case START:
      drawFullScreenImageDMA(Title);

      if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))
      {
        state = DRAWRULES;
        // fillScreenDMA(BLACK);
      }

      //Restate all values incase the player resets the game
      enemiesLeft = 3;

      player.health = 3;
      player.row = 9;
      player.col = 1;
      player.male = 0;
      player.female = 0;
      player.counter = 0;
      player.sprite = player.sprite1;

      enemy1.health = 1;
      enemy1.row = 2;
      enemy1.col = 2;
      enemy1.sprite = enemy1.sprite1;

      enemy2.health = 1;
      enemy2.row = 8;
      enemy2.col = 11;
      enemy2.sprite = enemy2.sprite1;

      boss.row = 16;
      boss.col = 160;
      boss.health = 1;
      boss.sprite = boss.sprite1;

      // state = ?
      break;

    // Draw the rules seperately so no tearing occurs
    case DRAWRULES:
      drawFullScreenImageDMA(RulesBackground);
      drawString(40, 5, "Hello My name is Armaan Lala", WHITE);
      drawString(50, 5, "This game is based off of Fire Embelem", WHITE);
      drawString(60, 5, "Use the D-pad to move on the screen", WHITE);
      drawString(70, 5, "Run into an enemy to fight them", WHITE);
      drawString(80, 5, "During a fight, pick Axe, Lance,", WHITE);
      drawString(90, 5, "or Sword", WHITE);
      drawString(100, 5, "(Rock,Paper,Scissors)", WHITE);
      drawString(110, 5, "You must defeat all enemies to win", WHITE);
      drawString(120, 5, "You have three lives, Good Luck!", WHITE);
      drawCenteredString(70, 0, 240, 160, "Press Start to continue", BLACK);
      state = RULES;
      break;

    case RULES:

      if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))
      {
        state = DRAWSELECT;
        // fillScreenDMA(BLACK);
      }
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
      {
        state = START;
        // fillScreenDMA(BLACK);
      }
      break;

    // Same as the the rules, draws the items only once to prevent tearing
    case DRAWSELECT:

      drawFullScreenImageDMA(CharacterSelect);
      drawCenteredString(30, 0, 240, 160, "Which gender would you like to play as?", WHITE);
      drawCenteredString(50, 80, 240, 160, "Boy", WHITE);
      drawCenteredString(50, -80, 240, 160, "Girl", WHITE);
      state = SELECT;

      break;

      //This is where the player selects their gender to play as
    case SELECT:
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
      {
        state = START;
        // fillScreenDMA(BLACK);
      }
      drawImageDMA(gender.row, gender.col, ARROW_WIDTH, ARROW_HEIGHT, Arrow);
      if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons))
      {
        gender.col = 180;
        drawRectDMA(gender.row, 16, 7, 7, BLACK);
      }
      if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons))
      {
        gender.col = 16;
        drawRectDMA(gender.row, 180, 7, 7, BLACK);
      }

      // These for loops are used for copying over the sprite templates so they only need to be copied now instead of creating seperate ones for male and female

      if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons))
      {
        if (gender.col == 16)
        {
          player.female = 1;
          for (int i = 0; i < 256; i++)
          {
            player.sprite1[i] = FemaleSprite[i];
            player.sprite2[i] = FemaleSprite2[i];
            player.sprite3[i] = FemaleSprite3[i];

            enemy1.sprite1[i] = Enemy1[i];
            enemy1.sprite2[i] = Enemy2[i];
            enemy1.sprite3[i] = Enemy3[i];

            enemy2.sprite1[i] = Enemy4[i];
            enemy2.sprite2[i] = Enemy5[i];
            enemy2.sprite3[i] = Enemy6[i];
          }
        }
        else if (gender.col == 180)
        {
          player.male = 1;

          for (int i = 0; i < 256; i++)
          {
            player.sprite1[i] = MaleSprite1[i];
            player.sprite2[i] = MaleSprite2[i];
            player.sprite3[i] = MaleSprite3[i];

            enemy1.sprite1[i] = Enemy1[i];
            enemy1.sprite2[i] = Enemy2[i];
            enemy1.sprite3[i] = Enemy3[i];

            enemy2.sprite1[i] = Enemy4[i];
            enemy2.sprite2[i] = Enemy5[i];
            enemy2.sprite3[i] = Enemy6[i];
          }
        }
        state = DRAWMAP;
        // fillScreenDMA(BLACK);
      }

      break;

      //Draws the background maps and determines whether the player has lost or won

    case DRAWMAP:

      rps.row = 126;
      rps.col = 16;

      if (enemy1.health == 0 && enemy2.health == 0 && boss.health == 0)
      {
        state = WIN;
      }

      else if (player.health == 3)
      {
        drawFullScreenImageDMA(Map);
        drawImageDMA(0, 225, FULLHEARTS_WIDTH, FULLHEARTS_HEIGHT, FullHearts);
        state = MAP;
      }
      else if (player.health == 2)
      {
        drawFullScreenImageDMA(Map);
        drawImageDMA(0, 225, FULLHEARTS_WIDTH, FULLHEARTS_HEIGHT, TwoHearts);
        state = MAP;
      }
      else if (player.health == 1)
      {
        drawFullScreenImageDMA(Map);
        drawImageDMA(0, 225, FULLHEARTS_WIDTH, FULLHEARTS_HEIGHT, OneHeart);
        state = MAP;
      }
      else if (player.health == 0)
      {
        state = LOSE;
      }
      if (enemy1.health == 0 && enemy2.health == 0 && boss.health == 0)
      {
        state = WIN;
      }
      // fillScreenDMA(BLACK);

      break;

    // Is in charge of moving the sprites and moving along the screen
    case MAP:

      enemiesLeft = boss.health + enemy1.health + enemy2.health;
      snprintf(left, sizeof(left), "%d enemies left", enemiesLeft);
      drawString(5, 5, left, BLACK);

      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
      {
        state = START;
      }

      //Start battle checks for collisions and starts a battle accordingly
      startBattle(&player, &enemy1, &enemy2, &boss, &state);

      // Have to draw boss first to avoid weird tearing.
      if (enemy1.health == 1)
      {
        drawImageDMA(enemy1.row * 16, enemy1.col * 16, 16, 16, enemy1.sprite);
      }

      if (enemy2.health == 1)
      {
        drawImageDMA(enemy2.row * 16, enemy2.col * 16, 16, 16, enemy2.sprite);
      }

      if (boss.health == 1)
      {
        drawImageDMA(boss.row, boss.col, BOSS1_WIDTH, BOSS1_HEIGHT, boss.sprite);
      }

      drawImageDMA(player.row * 16, player.col * 16, 16, 16, player.sprite);

      if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons) && player.row < 9 && checkBounds(player.row + 1, player.col) == 1)
      {
        drawBackgroundImageDMA(player.row * 16, player.col * 16, 16, 16, Map);
        player.row += 1;
      }

      if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons) && player.row >= 1 && checkBounds(player.row - 1, player.col) == 1)
      {
        drawBackgroundImageDMA(player.row * 16, player.col * 16, 16, 16, Map);
        player.row -= 1;
      }

      if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons) && player.col < 14 && checkBounds(player.row, player.col + 1) == 1)
      {
        drawBackgroundImageDMA(player.row * 16, player.col * 16, 16, 16, Map);
        player.col += 1;
      }

      if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons) && player.col >= 1 && checkBounds(player.row, player.col - 1) == 1)
      {
        drawBackgroundImageDMA(player.row * 16, player.col * 16, 16, 16, Map);
        player.col -= 1;
      }

      // Cycles between the sprites every 30 frames
      if (vBlankCounter % 30 == 0)
      {
        changeSprite(&player);
        changeSprite(&enemy1);
        changeSprite(&enemy2);
        changeSpriteBoss(&boss);
      }

      break;

      // In charge of doing the animation for a fight
    case GRASSANIM:

      fillScreenDMA(BLACK);

      for (int i = 0; i < 120; i += 2)
      {
        waitForVBlank();
        for (int j = 0; j < 240; j += 2)
        {
          drawBackgroundImageDMA(i, j, 2, 1, BattleGrass);
        }
      }
      for (int i = 1; i < 120; i += 2)
      {
        waitForVBlank();
        for (int j = 1; j < 240; j += 2)
        {
          drawBackgroundImageDMA(i, j, 2, 1, BattleGrass);
        }
      }

      state = FIGHT;
      break;

      // This is only for fights that are not the boss
    case FIGHT:
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
      {
        state = START;
      }

      if (player.row == 2 && player.col == 2)
      {
        drawImageDMA(32, 176, 64, 64, Pirate);
      }
      else if (player.row == 8 && player.col == 11)
      {
        drawImageDMA(20, 160, 64, 64, Sniper);
      }
      if (player.female == 1)
      {
        drawImageDMA(48, 16, 64, 64, FemaleFight);
      }
      else if (player.male == 1)
      {
        drawImageDMA(48, 16, 64, 64, MaleFight);
      }

      // This is how you pick the option for the fight
      drawCenteredString(50, 0, 240, 160, "Lance", WHITE);
      drawCenteredString(50, 80, 240, 160, "Sword", WHITE);
      drawCenteredString(50, -80, 240, 160, "Axe", WHITE);
      drawImageDMA(rps.row, rps.col, ARROW_WIDTH, ARROW_HEIGHT, Arrow);

      // Determines the exact spaces for the arrow to be in
      if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons) && rps.col == 90)
      {
        rps.col = 170;
        drawRectDMA(rps.row, 90, 7, 7, BLACK);
      }

      else if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons) && rps.col == 16)
      {
        rps.col = 90;
        drawRectDMA(rps.row, 16, 7, 7, BLACK);
      }

      else if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons) && rps.col == 90)
      {
        rps.col = 16;
        drawRectDMA(rps.row, 90, 7, 7, BLACK);
      }
      else if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons) && rps.col == 170)
      {
        rps.col = 90;
        drawRectDMA(rps.row, 170, 7, 7, BLACK);
      }

      // Determines the enemy's option and determines whether you win or lose the fight
      if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons))
      {

        int enemy = randint(1, 4);
        if (enemy == 4)
        {
          enemy = 3;
        }

        if (rps.col == 90)
        {

          if (enemy == 2)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked lance", WHITE);
            drawCenteredString(70, 0, 240, 160, "Its a tie", WHITE);
            player.row++;
            state = WAIT;
          }
          else if (enemy == 3)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked sword", WHITE);
            drawCenteredString(70, 0, 240, 160, "You won this fight", WHITE);
            if (player.row == 2 && player.col == 2)
            {
              enemy1.health--;
              state = WAIT;
            }
            else if (player.row == 8 && player.col == 11)
            {
              enemy2.health--;
              state = WAIT;
            }
          }
          else if (enemy == 1)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked axe", WHITE);
            drawCenteredString(70, 0, 240, 160, "You lost this fight", WHITE);

            player.health--;
            player.row++;
            state = WAIT;
          }
        }
        else if (rps.col == 170)
        {

          if (enemy == 2)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked lance", WHITE);
            drawCenteredString(70, 0, 240, 160, "You lost this fight", WHITE);
            player.health--;
            player.row++;
            state = WAIT;
          }
          else if (enemy == 3)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked sword", WHITE);
            drawCenteredString(70, 0, 240, 160, "Its a tie", WHITE);
            player.row++;
            state = WAIT;
          }
          else if (enemy == 1)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked axe", WHITE);
            drawCenteredString(70, 0, 240, 160, "You won this fight", WHITE);
            if (player.row == 2 && player.col == 2)
            {
              enemy1.health--;
              state = WAIT;
            }
            else if (player.row == 8 && player.col == 11)
            {
              enemy2.health--;
              state = WAIT;
            }
          }
        }
        else if (rps.col == 16)
        {

          if (enemy == 2)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked lance", WHITE);
            drawCenteredString(70, 0, 240, 160, "You won this fight", WHITE);
            if (player.row == 2 && player.col == 2)
            {
              enemy1.health--;
              state = WAIT;
            }
            else if (player.row == 8 && player.col == 11)
            {
              enemy2.health--;
              state = WAIT;
            }
          }
          else if (enemy == 3)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked sword", WHITE);
            drawCenteredString(70, 0, 240, 160, "You lost this fight", WHITE);
            player.health--;
            player.row++;
            state = WAIT;
          }
          else if (enemy == 1)
          {
            drawCenteredString(60, 0, 240, 160, "The enemy picked axe", WHITE);
            drawCenteredString(70, 0, 240, 160, "Its a tie", WHITE);
            player.row++;
            state = WAIT;
          }
        }
      }

      break;

      // Same animation as before, just for the castle background now
    case CASTLEANIM:
      fillScreenDMA(BLACK);

      for (int i = 0; i < 120; i += 2)
      {
        waitForVBlank();
        for (int j = 0; j < 240; j += 2)
        {
          drawBackgroundImageDMA(i, j, 2, 1, BattleCastle);
        }
      }
      for (int i = 1; i < 120; i += 2)
      {
        waitForVBlank();
        for (int j = 1; j < 240; j += 2)
        {
          drawBackgroundImageDMA(i, j, 2, 1, BattleCastle);
        }
      }
      state = BOSSFIGHT;
      break;

      // Same fight mechanics as above, just had to modify it since the text is different and the background is different
    case BOSSFIGHT:
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
      {
        state = START;
      }

      drawImageDMA(32, 130, GENERAL_WIDTH, GENERAL_HEIGHT, General);

      if (player.female == 1)
      {
        drawImageDMA(48, 16, 64, 64, FemaleCastle);
      }
      else if (player.male == 1)
      {
        drawImageDMA(48, 16, 64, 64, MaleCastle);
      }

      drawCenteredString(50, 0, 240, 160, "Lance", WHITE);
      drawCenteredString(50, 80, 240, 160, "Sword", WHITE);
      drawCenteredString(50, -80, 240, 160, "Axe", WHITE);
      drawImageDMA(rps.row, rps.col, ARROW_WIDTH, ARROW_HEIGHT, Arrow);

      if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons) && rps.col == 90)
      {
        rps.col = 170;
        drawRectDMA(rps.row, 90, 7, 7, BLACK);
      }

      else if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons) && rps.col == 16)
      {
        rps.col = 90;
        drawRectDMA(rps.row, 16, 7, 7, BLACK);
      }

      else if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons) && rps.col == 90)
      {
        rps.col = 16;
        drawRectDMA(rps.row, 90, 7, 7, BLACK);
      }
      else if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons) && rps.col == 170)
      {
        rps.col = 90;
        drawRectDMA(rps.row, 170, 7, 7, BLACK);
      }

      if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons))
      {

        int enemy = randint(1, 4);
        if (enemy == 4)
        {
          enemy = 3;
        }
        if (rps.col == 90)
        {

          if (enemy == 2)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked lance", WHITE);
            drawCenteredString(70, 0, 240, 160, "Its a tie", WHITE);
            player.row++;
            state = WAIT;
          }
          else if (enemy == 3)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked sword", WHITE);
            drawCenteredString(70, 0, 240, 160, "You won this fight", WHITE);
            boss.health--;
            state = WAIT;
          }
          else if (enemy == 1)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked axe", WHITE);
            drawCenteredString(70, 0, 240, 160, "You lost this fight", WHITE);

            player.health--;
            player.row++;
            state = WAIT;
          }
        }
        else if (rps.col == 170)
        {

          if (enemy == 2)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked lance", WHITE);
            drawCenteredString(70, 0, 240, 160, "You lost this fight", WHITE);
            player.health--;
            player.row++;
            state = WAIT;
          }
          else if (enemy == 3)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked sword", WHITE);
            drawCenteredString(70, 0, 240, 160, "Its a tie", WHITE);
            player.row++;
            state = WAIT;
          }
          else if (enemy == 1)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked axe", WHITE);
            drawCenteredString(70, 0, 240, 160, "You won this fight", WHITE);
            boss.health--;
            state = WAIT;
          }
        }
        else if (rps.col == 16)
        {

          if (enemy == 2)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked lance", WHITE);
            drawCenteredString(70, 0, 240, 160, "You won this fight", WHITE);
            boss.health--;
            state = WAIT;
          }
          else if (enemy == 3)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked sword", WHITE);
            drawCenteredString(70, 0, 240, 160, "You lost this fight", WHITE);
            player.health--;
            player.row++;
            state = WAIT;
          }
          else if (enemy == 1)
          {
            drawCenteredString(60, 0, 240, 160, "The boss picked axe", WHITE);
            drawCenteredString(70, 0, 240, 160, "Its a tie", WHITE);
            player.row++;
            state = WAIT;
          }
        }
      }

      break;

    // This case is just used to prevent the game from going too fast and skipping text
    case WAIT:
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
      {
        state = START;
      }
      if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons))
      {
        state = DRAWMAP;
      }
      break;

    // The case once the player has beaten all the enemies
    case WIN:
      drawFullScreenImageDMA(Win);
      drawCenteredString(50, 0, 240, 160, "Press START to play again", WHITE);
      if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) || KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
      {
        state = START;
      }
      break;

    //The case when the player runs out of lives
    case LOSE:
      drawFullScreenImageDMA(Lose);
      drawCenteredString(50, 0, 240, 160, "Press START to try again", RED);
      if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) || KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))
      {
        state = START;
      }
      break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}

// Looks at the players coordinates and determines whether or not the player should enter a fight
// Yes I know this is super bad convention. I dont have the patience to go through and implement a better solution before the deadline
void startBattle(Character *a, Character *b, Character *c, Boss *d, GBAState *state)
{

  if (a->row == 2 && a->col == 2 && b->health == 1)
  {
    *state = GRASSANIM;
  }
  else if (a->row == 8 && a->col == 11 && c->health == 1)
  {
    *state = GRASSANIM;
  }
  else if (a->row == 2 && a->col == 11 && d->health == 1)
  {
    *state = CASTLEANIM;
  }
}

// Cycles through the character sprites whenever called
void changeSprite(Character *a)
{
  a->counter++;
  if ((a->counter) % 3 == 0)
  {
    a->sprite = a->sprite1;
  }
  else if ((a->counter) % 3 == 1)
  {
    a->sprite = a->sprite2;
  }
  else if ((a->counter) % 3 == 2)
  {
    a->sprite = a->sprite3;
  }
}

// Had to make a seperate method as the Boss sprites are different size
void changeSpriteBoss(Boss *a)
{
  a->counter++;
  if ((a->counter) % 3 == 0)
  {
    a->sprite = a->sprite1;
  }
  else if ((a->counter) % 3 == 1)
  {
    a->sprite = a->sprite2;
  }
  else if ((a->counter) % 3 == 2)
  {
    a->sprite = a->sprite3;
  }
}

// Checks if the player can move to a particular space
// Can be super optimized if I used a 2D array of booleans but I am too tired
int checkBounds(int row, int col)
{
  if (row == 9 && col == 4)
  {
    return 0;
  }
  else if (row == 8 && col == 4)
  {
    return 0;
  }
  else if (row == 7 && col == 4)
  {
    return 0;
  }
  else if (row == 7 && col == 5)
  {
    return 0;
  }
  else if (row == 6 && col == 5)
  {
    return 0;
  }
  else if (row == 5 && col == 5)
  {
    return 0;
  }
  else if (row == 0 && col == 8)
  {
    return 0;
  }
  else if (row == 1 && col == 8)
  {
    return 0;
  }
  else if (row == 2 && col == 8)
  {
    return 0;
  }
  else if (row == 3 && col == 8)
  {
    return 0;
  }
  else if (row == 4 && col == 8)
  {
    return 0;
  }
  else if (row == 5 && col == 8)
  {
    return 0;
  }
  else if (row == 6 && col == 8)
  {
    return 0;
  }
  else if (row == 7 && col == 8)
  {
    return 0;
  }
  else if (row == 0 && col == 14)
  {
    return 0;
  }
  else if (row == 1 && col == 14)
  {
    return 0;
  }
  else if (row == 2 && col == 14)
  {
    return 0;
  }
  else if (row == 3 && col == 14)
  {
    return 0;
  }
  else if (row == 4 && col == 14)
  {
    return 0;
  }
  else if (row == 5 && col == 14)
  {
    return 0;
  }
  else if (row == 6 && col == 14)
  {
    return 0;
  }
  else if (row == 7 && col == 14)
  {
    return 0;
  }
  else if (row == 7 && col == 13)
  {
    return 0;
  }
  else if (row == 7 && col == 12)
  {
    return 0;
  }
  else if (row == 7 && col == 10)
  {
    return 0;
  }
  else if (row == 7 && col == 9)
  {
    return 0;
  }
  else if (row == 6 && col == 13)
  {
    return 0;
  }
  else if (row == 6 && col == 12)
  {
    return 0;
  }
  else if (row == 6 && col == 10)
  {
    return 0;
  }
  else if (row == 6 && col == 9)
  {
    return 0;
  }
  else if (row == 0 && col == 13)
  {
    return 0;
  }
  else if (row == 0 && col == 12)
  {
    return 0;
  }
  else if (row == 0 && col == 10)
  {
    return 0;
  }
  else if (row == 0 && col == 9)
  {
    return 0;
  }
  else if (row == 3 && col == 10)
  {
    return 0;
  }
  else if (row == 3 && col == 12)
  {
    return 0;
  }
  else if (row == 0 && col == 11)
  {
    return 0;
  }

  return 1;
}
